allbus/thebus/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import bus_views
from .views import stop_views
from .views import trip_views

app_name = 'thebus'
urlpatterns = [
    # stop views
    url(r'^stops/?$', stop_views.stop_search, name="stop_search"),

    url(r'^(?P<stop_id>\d+)/?$', stop_views.stop_details, {'route': None},
        name="stop_details_no_route"),

    url(r'^(?P<stop_id>\d+):(?P<route>[a-zA-Z0-9]+)/?$',
        stop_views.stop_details,
        name="stop_details"),

    url(r'^(?P<stop_id>\d+):(?P<route>[a-zA-Z0-9]+)/bus/(?P<bus>\d+)/trip/(?P<trip_id>[\d\w\.]+)/?$',
        stop_views.stop_bus_map,
        name="stop_bus_map"),

    url(r'^(?P<stop_id>\d+):(?P<route>[a-zA-Z0-9]+)/trip/(?P<trip_id>[\d\w\.]+)/?$',
        stop_views.stop_bus_map,
        name="stop_bus_map"),

    url(r'^es/near/(?P<latitude>[\-\.0-9]+)/(?P<longitude>[\-\.0-9]+)/?$',
        stop_views.stop_nearby,
        name="stop_nearby"),

    # bus views
    url(r'^buses/?$',
        bus_views.all_buses,
        name="all_buses"),

    url(r'^buses/(?P<bus>[\d]+)/?$',
        bus_views.bus_details,
        name="bus_details"),

    # trip views
    url(r'^trips/(?P<trip_id>[\d\.]+)/?$',
        trip_views.trip_details,
        name="trip_details"),
]

# vim: filetype=python

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import bad_request
from django.views.defaults import page_not_found
from django.views.defaults import permission_denied
from django.views.defaults import server_error
from django.views.generic import TemplateView


urlpatterns = [
    # Web urls
    url(r'^', include("allbus.www.urls")),

    # Allbus urls
    url(r'^', include("allbus.thebus.urls")),

    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # GTFS Explorer
    url(r'^explore$', TemplateView.as_view(template_name="explore/home.html"),
        name='home'),
    url(r'^explore/', include('allbus.exploreapp.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

    urlpatterns += [
        url(r'^400/$', bad_request),
        url(r'^403/$', permission_denied),
        url(r'^404/$', page_not_found),
        url(r'^500/$', server_error)
    ]

allbus/thebus/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
from managers import TheBusStopManager
from managers import TheBusTripManager
from multigtfs.models import Stop
from multigtfs.models import Trip


class TheBusStop(Stop):

    class Meta:
        proxy = True

    objects = TheBusStopManager()

    def to_dict(self):
        return {
            'stop_id': self.stop_id,
            'name': self.name,
            'latitude': self.point.y,
            'longitude': self.point.x,
            'url': self.url
        }


class TheBusTrip(Trip):

    class Meta:
        proxy = True

    objects = TheBusTripManager()

    def __init__(self, *args, **kwargs):
        super(TheBusTrip, self).__init__(*args, **kwargs)

    def get_stop_times(self):
        return [x for x in self.stoptime_set.all()]

    def get_stops(self):
        return [x.stop for x in self.stoptime_set.all().only('stop')]

    def get_previous_stop(self, stop_id):
        stop_id_index = self._get_index_of_stop_id_in_trip(stop_id)
        if stop_id_index is not None and stop_id_index != 0:
            return list(self.stoptime_set.all())[stop_id_index - 1].stop
        else:
            return None

    def get_next_stop(self, stop_id):
        stop_id_index = self._get_index_of_stop_id_in_trip(stop_id)
        if stop_id_index is not None \
                and stop_id_index != self.stoptime_set.all().count() - 1:
            return list(self.stoptime_set.all())[stop_id_index + 1].stop
        else:
            return None

    def to_dict(self):
        return {
            'trip_id': self.trip_id,
            'route_id': self.route.route_id,
            'route_shortname': self.route.short_name,
            'route_longname': self.route.long_name,
            'geojson': json.loads(self.geometry.geojson),
            'headsign': self.headsign
        }

    def _get_index_of_stop_id_in_trip(self, stop_id):
        stop_id_index = [
            i for i, stop_time in enumerate(self.stoptime_set.all())
            if stop_time.stop.stop_id == stop_id]

        if len(stop_id_index) == 1:
            return stop_id_index[0]
        else:
            return None

# vim: filetype=python

allbus/thebus/views/bus_views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import datetime
from django.conf import settings
from django.http import Http404
from django.http import HttpResponse

import json
from ..utilities.client import parse_xml_to_dict
from ..utilities.client import TheBusClient
from ..utilities.time_utilities import naive_to_timestamp


def all_buses(request):
    c = TheBusClient(settings.THEBUS_API_CLIENT_TOKEN)
    gtfs_vl = c.get_gtfs_vehicle_location()
    vl = [{'id': v.id,
           'latitude': v.vehicle.position.latitude,
           'longitude': v.vehicle.position.longitude} for v in gtfs_vl.entity]
    return HttpResponse(json.dumps(vl), content_type="application/json")


def bus_details(request, bus):
    c = TheBusClient(settings.THEBUS_API_CLIENT_TOKEN)
    v_json = c.track_vehicle(int(bus), parse_xml_to_dict)
    vehicles = v_json.get('vehicles', None)
    vehicle = vehicles.get('vehicle', None)

    if vehicle:
        if 'last_message' in vehicle:
            naive_datetime = datetime.datetime.strptime(
                vehicle['last_message'],
                "%m/%d/%Y %I:%M:%S %p")
            vehicle['last_message_ts'] = naive_to_timestamp(
                naive_datetime, tz='Pacific/Honolulu')

        return HttpResponse(json.dumps(vehicle), content_type="application/json")
    else:
        raise Http404("Unable to find Bus {}".format(str(bus)))

# vim: filetype=python

allbus/thebus/views/stop_views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from collections import Counter
import datetime
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from ..models import TheBusStop
from ..models import TheBusTrip
import json
from ..utilities.client import parse_vehicle_xml_to_dict
from ..utilities.client import parse_xml_to_dict
from ..utilities.client import TheBusClient
from ..utilities.time_utilities import naive_to_timestamp


STRIP_CONNECTORS = ['or', 'and', 'near', '+', '&']


def stop_details(request, stop_id, route=None):
    c = TheBusClient(settings.THEBUS_API_CLIENT_TOKEN)
    s = get_object_or_404(TheBusStop, stop_id=stop_id)
    a = c.get_arrivals(int(stop_id), parse_xml_to_dict)

    stopTimes = a.get('stopTimes', None)
    arrivals = stopTimes.get('arrival', None) if stopTimes else None

    if route:
        route = route.upper()
        if arrivals:
            arrivals = filter(lambda x: x['route'] == route, arrivals)

    output = {
        'stop': s.to_dict(),
        'arrivals': arrivals,
        'servertime': stopTimes.get('timestamp')
    }

    try:
        naive_datetime = datetime.datetime.strptime(
            output['servertime'],
            "%m/%d/%Y %I:%M:%S %p")
        output['servertime_ts'] = naive_to_timestamp(
            naive_datetime, tz='Pacific/Honolulu')
    except:
        pass

    if route:
        output['route'] = route

    output['route_names'] = list(TheBusStop.objects.get_route_names(stop_id))

    return HttpResponse(json.dumps(output), content_type="application/json")


def stop_nearby(request, latitude, longitude):
    stops = TheBusStop.objects.nearby(float(latitude), float(longitude))
    stops_as_json = [s.to_dict() for s in stops] if stops else []

    return HttpResponse(json.dumps(stops_as_json), content_type="application/json")


def stop_search(request):
    query = request.GET.get('q', None)
    stops = TheBusStop.objects.search(query) if query else None
    counter = Counter(stops)

    output = {
        'stops': [s.to_dict() for s, c in counter.most_common()],
        'query': query
    }

    return HttpResponse(json.dumps(output), content_type="application/json")


def stop_bus_map(request, stop_id, route, trip_id, bus = None):
    s = get_object_or_404(TheBusStop, stop_id=stop_id)
    trip = TheBusTrip.objects.get(trip_id=trip_id)
    stops = trip.get_stops()

    if bus:
        c = TheBusClient(settings.THEBUS_API_CLIENT_TOKEN)
        v = c.track_vehicle(int(bus), parse_vehicle_xml_to_dict)
        vehicle = v.get('vehicles', None)
        vehicle = vehicle[0] if len(vehicle) == 1 else vehicle
    else:
        vehicle = None

    output = {'stop': s.to_dict(),
              'vehicle': vehicle,
              'trip': trip.to_dict(),
              'stops': [{'stop_id': s.stop_id, 'name': s.name, 'point': { 'x': s.point.x, 'y': s.point.y}} for s in stops]}

    return HttpResponse(json.dumps(output), content_type="application/json")


# vim: filetype=python

allbus/thebus/views/trip_views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
import json
from ..models import TheBusTrip


def trip_details(request, trip_id):
    t = get_object_or_404(TheBusTrip, trip_id=trip_id)
    return HttpResponse(json.dumps(t.to_dict()), content_type="application/json")

# vim: filetype=python

allbus/thebus/templates/stops/details.html
{% extends 'base.html' %}

{% block page_title %}
Stop {{ stop.stop_id }} @ {{ stop.name }}
{% endblock page_title %}

{% block content %}
<ul>
  <li>
  {% for route_name in route_names %}
  {{ route_name }}
  {% endfor %}
  </li>
</ul>

<ul>
  {% for arrival in  arrivals %}
  <li>
    {% if arrival.vehicle != '???' %}
    <a href="{% url 'thebus:stop_bus_map' stop.stop_id arrival.route arrival.vehicle arrival.trip %}" data-ignore="push"> 
    {% endif %}
    <div class="route">
        <h1>{{ arrival.route }}</h1>
        <p class="bus">
            {% if arrival.vehicle == '???' %}
            No GPS
            {% else %}
            Bus {{ arrival.vehicle }}
            {% endif %}
        </p>
    </div>
    <div class="info">
        <h4 class="headsign">{{ arrival.headsign }}</h4>
        <p class="arrival_time">
        <span class="wait">{{ arrival.stopTime }}</span>
        </p>
    </div>
    {% if arrival.vehicle != '???' %}
    </a>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

allbus/thebus/templates/stops/stop_bus_map.html
{% extends 'base.html' %}

{% load compress %}{% load staticfiles i18n %}

{% block css %}
    {{ block.super }}
    <link href="{% static 'js/leaflet/leaflet.css' %}" rel="stylesheet"/>
{% endblock css %}

{% block page_title %}
Map of Stop {{ stop.stop_id }} @ {{ stop.name }}
{% endblock page_title %}

{% block content %}
<div id="stops">
    <ul>
    {% for s in stops %}
        <li>
            {% if stop.stop_id == s.stop_id %}
            {% else %}
            <a href="{% url 'thebus:stop_details_no_route' s.stop_id %}">{{ s.stop_id}} - {{s.name}}</a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
</div>
<div id="map"></div>
{% endblock content %}

{% block compressed-js %}
    {{ block.super }}
    <script src="{% static 'js/leaflet/leaflet.js' %}"></script>
    <script src="{% static 'js/leaflet-polylinedecorator/leaflet.polylineDecorator.js' %}"></script>
{% endblock compressed-js %}

{% block inline-js %}
    {{ block.super }}
    <script type="text/javascript">
        var map;
        var markers = [];
        var stop_coordinates = {
            "latitude": {{ stop.point.y }},
            "longitude": {{ stop.point.x }}
        };

        function initialize_map() {
            map = L.map('map');
            map.setView(
                    L.latLng(
                        stop_coordinates["latitude"],
                        stop_coordinates["longitude"]), 16);
            L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
                maxZoom: 18,
            }).addTo(map);
            var geoJsonStyle = {
                "color": "#ff7800",
                "weight": 2,
                "opacity": 0.6
            };
            var geoJson = {{ trip.geometry.geojson | safe}};
            L.geoJson(geoJson, { style: geoJsonStyle }).addTo(map);

            var latlngs = L.GeoJSON.coordsToLatLngs(geoJson["coordinates"], 0);
            var arrows = L.polyline(latlngs, {});
            var arrowHead = L.polylineDecorator(arrows, {
                patterns: [
                    {repeat: 100, symbol:
                        L.Symbol.arrowHead({pixelSize: 12, pathOptions:
                            {color:"#000", fillOpacity: .7, weight: 0}})}
                ]
            }).addTo(map);
        }

        function create_marker(map, stop_id, stop_url, latlng) {
            var iconPointX = (stop_id.toString().length > 3) ? 30 : 24;
            var iconHtml = '<a href="' + stop_url + '">' + stop_id + '</a>';
            var divIcon = L.divIcon({className: 'stop-icon', iconSize: new L.Point(iconPointX,18), html: iconHtml});
            var markerOptions = { icon: divIcon };
            var marker = L.marker(latlng, markerOptions);
            marker.addTo(map);
            markers.push(marker);
        }

        initialize_map();

        create_marker(map, {{stop.stop_id}}, "{% url "thebus:stop_details_no_route" stop.stop_id %}", new L.latLng({{stop.point.y}}, {{stop.point.x}}));

        var stops = [{% for s in stops %}[{{s.point.y}}, {{s.point.x}}, {{s.stop_id}}, "{% url "thebus:stop_details_no_route" s.stop_id %}",],{% endfor %}];

        for (var i = 0; i < stops.length; i++)
        {
            create_marker(map, stops[i][2], stops[i][3], new L.latLng(stops[i][0], stops[i][1]));
        }

        map.on('zoomend', function() {
            var currentZoom = map.getZoom();
            for (var i = 0; i < markers.length; i++)
            {
                if (currentZoom > 14)
                {
                    markers[i].setRadius(6);
                }
                else
                {
                    markers[i].setRadius((6/currentZoom) * 6);
                }
            }
        });
    </script>
{% endblock inline-js %}